default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: crypto_currency_valuation_development

test:
  <<: *default
  database: crypto_currency_valuation_test

production:
  <<: *default
  database: crypto_currency_valuation
  username: <%= ENV['CRYPTO_CURRENCY_VALUATION_DATABASE_USER'] %>
  password: <%= ENV['CRYPTO_CURRENCY_VALUATION_DATABASE_PASS'] %>
